package com.gym.enterprise_system.repository;

import com.gym.enterprise_system.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

@Repository
public interface UserRepository extends JpaRepository<User, UUID> {
    // Custom query method: implementation is auto-generated by Spring!
    Optional<User> findByEmail(String email);

    boolean existsByEmail(String email);

    Long countByIsActiveTrue();
}